version: '2'
services:
    imventas-app:
        image: imventas
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://imventas-mariadb:3306/imventas
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    imventas-mariadb:
        extends:
            file: mariadb.yml
            service: imventas-mariadb
